<Project>
  <PropertyGroup>
    <DefaultItemExcludes>$(DefaultItemExcludes);**\artifacts\**</DefaultItemExcludes>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="artifacts\**\*.cs" />
    <EmbeddedResource Remove="artifacts\**\*" />
    <None Remove="artifacts\**\*" />
    <Page Remove="artifacts\**\*.xaml" />
  </ItemGroup>
</Project>
