// <auto-generated />
using System;
using ClosetApp.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClosetApp.Infrastructure.Migrations
{
    [DbContext(typeof(ClosetDbContext))]
    [Migration("20260607095947_AddLocalUsers")]
    partial class AddLocalUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("ClosetApp.Domain.Entities.Clothing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FavoriteLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GarmentType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LocalUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("Season")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LocalUserId");

                    b.ToTable("Clothes");
                });

            modelBuilder.Entity("ClosetApp.Domain.Entities.ClothingTag", b =>
                {
                    b.Property<Guid>("ClothingId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TagId")
                        .HasColumnType("TEXT");

                    b.HasKey("ClothingId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ClothingTags");
                });

            modelBuilder.Entity("ClosetApp.Domain.Entities.Favorite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LocalUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OutfitId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LocalUserId");

                    b.HasIndex("OutfitId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("ClosetApp.Domain.Entities.LocalUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarPhotoPath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LinkedAccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Role");

                    b.ToTable("LocalUsers");
                });

            modelBuilder.Entity("ClosetApp.Domain.Entities.Outfit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LocalUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("OriginalClothingCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Scene")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Season")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("WearCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("WornDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LocalUserId");

                    b.ToTable("Outfits");
                });

            modelBuilder.Entity("ClosetApp.Domain.Entities.OutfitClothing", b =>
                {
                    b.Property<Guid>("OutfitId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClothingId")
                        .HasColumnType("TEXT");

                    b.HasKey("OutfitId", "ClothingId");

                    b.HasIndex("ClothingId");

                    b.ToTable("OutfitClothes");
                });

            modelBuilder.Entity("ClosetApp.Domain.Entities.OutfitGeneratedImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureReason")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("LocalUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OptionSnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OutfitId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OutfitSnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileSnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultImagePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LocalUserId");

                    b.HasIndex("OutfitId");

                    b.ToTable("OutfitGeneratedImages");
                });

            modelBuilder.Entity("ClosetApp.Domain.Entities.OutfitWornRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ClothingCountSnapshot")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClothingDetailsSnapshot")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSnapshotComplete")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("LocalUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OutfitClothingIdsSnapshot")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OutfitId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OutfitNameSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviewSnapshotPath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("WornDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LocalUserId");

                    b.HasIndex("OutfitId");

                    b.ToTable("OutfitWornRecords");
                });

            modelBuilder.Entity("ClosetApp.Domain.Entities.PersonalProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarPhotoPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("AvoidKeywords")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BodyShape")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CloudUploadConsentAcceptedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FaceFeaturesSummary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullBodyPhotoPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("HairColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HairLength")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("HeightCm")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("LocalUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SkinTone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StyleKeywords")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LocalUserId");

                    b.ToTable("PersonalProfiles");
                });

            modelBuilder.Entity("ClosetApp.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LocalUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LocalUserId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("ClosetApp.Domain.Entities.Clothing", b =>
                {
                    b.HasOne("ClosetApp.Domain.Entities.LocalUser", "LocalUser")
                        .WithMany("Clothes")
                        .HasForeignKey("LocalUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("LocalUser");
                });

            modelBuilder.Entity("ClosetApp.Domain.Entities.ClothingTag", b =>
                {
                    b.HasOne("ClosetApp.Domain.Entities.Clothing", "Clothing")
                        .WithMany("ClothingTags")
                        .HasForeignKey("ClothingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClosetApp.Domain.Entities.Tag", "Tag")
                        .WithMany("ClothingTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clothing");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("ClosetApp.Domain.Entities.Favorite", b =>
                {
                    b.HasOne("ClosetApp.Domain.Entities.LocalUser", "LocalUser")
                        .WithMany("Favorites")
                        .HasForeignKey("LocalUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ClosetApp.Domain.Entities.Outfit", "Outfit")
                        .WithMany("Favorites")
                        .HasForeignKey("OutfitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LocalUser");

                    b.Navigation("Outfit");
                });

            modelBuilder.Entity("ClosetApp.Domain.Entities.Outfit", b =>
                {
                    b.HasOne("ClosetApp.Domain.Entities.LocalUser", "LocalUser")
                        .WithMany("Outfits")
                        .HasForeignKey("LocalUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("LocalUser");
                });

            modelBuilder.Entity("ClosetApp.Domain.Entities.OutfitClothing", b =>
                {
                    b.HasOne("ClosetApp.Domain.Entities.Clothing", "Clothing")
                        .WithMany("OutfitClothes")
                        .HasForeignKey("ClothingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClosetApp.Domain.Entities.Outfit", "Outfit")
                        .WithMany("OutfitClothes")
                        .HasForeignKey("OutfitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clothing");

                    b.Navigation("Outfit");
                });

            modelBuilder.Entity("ClosetApp.Domain.Entities.OutfitGeneratedImage", b =>
                {
                    b.HasOne("ClosetApp.Domain.Entities.LocalUser", "LocalUser")
                        .WithMany("OutfitGeneratedImages")
                        .HasForeignKey("LocalUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ClosetApp.Domain.Entities.Outfit", "Outfit")
                        .WithMany("GeneratedImages")
                        .HasForeignKey("OutfitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LocalUser");

                    b.Navigation("Outfit");
                });

            modelBuilder.Entity("ClosetApp.Domain.Entities.OutfitWornRecord", b =>
                {
                    b.HasOne("ClosetApp.Domain.Entities.LocalUser", "LocalUser")
                        .WithMany("WornRecords")
                        .HasForeignKey("LocalUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ClosetApp.Domain.Entities.Outfit", "Outfit")
                        .WithMany("WornRecords")
                        .HasForeignKey("OutfitId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LocalUser");

                    b.Navigation("Outfit");
                });

            modelBuilder.Entity("ClosetApp.Domain.Entities.PersonalProfile", b =>
                {
                    b.HasOne("ClosetApp.Domain.Entities.LocalUser", "LocalUser")
                        .WithMany("PersonalProfiles")
                        .HasForeignKey("LocalUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("LocalUser");
                });

            modelBuilder.Entity("ClosetApp.Domain.Entities.Tag", b =>
                {
                    b.HasOne("ClosetApp.Domain.Entities.LocalUser", "LocalUser")
                        .WithMany("Tags")
                        .HasForeignKey("LocalUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("LocalUser");
                });

            modelBuilder.Entity("ClosetApp.Domain.Entities.Clothing", b =>
                {
                    b.Navigation("ClothingTags");

                    b.Navigation("OutfitClothes");
                });

            modelBuilder.Entity("ClosetApp.Domain.Entities.LocalUser", b =>
                {
                    b.Navigation("Clothes");

                    b.Navigation("Favorites");

                    b.Navigation("OutfitGeneratedImages");

                    b.Navigation("Outfits");

                    b.Navigation("PersonalProfiles");

                    b.Navigation("Tags");

                    b.Navigation("WornRecords");
                });

            modelBuilder.Entity("ClosetApp.Domain.Entities.Outfit", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("GeneratedImages");

                    b.Navigation("OutfitClothes");

                    b.Navigation("WornRecords");
                });

            modelBuilder.Entity("ClosetApp.Domain.Entities.Tag", b =>
                {
                    b.Navigation("ClothingTags");
                });
#pragma warning restore 612, 618
        }
    }
}
