// <auto-generated />
using System;
using ClosetApp.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClosetApp.Infrastructure.Migrations
{
    [DbContext(typeof(ClosetDbContext))]
    partial class ClosetDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("ClosetApp.Domain.Entities.Clothing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FavoriteLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GarmentType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("Season")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clothes");
                });

            modelBuilder.Entity("ClosetApp.Domain.Entities.ClothingTag", b =>
                {
                    b.Property<Guid>("ClothingId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TagId")
                        .HasColumnType("TEXT");

                    b.HasKey("ClothingId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ClothingTags");
                });

            modelBuilder.Entity("ClosetApp.Domain.Entities.Favorite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OutfitId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OutfitId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("ClosetApp.Domain.Entities.Outfit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Scene")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Season")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("WearCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("WornDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Outfits");
                });

            modelBuilder.Entity("ClosetApp.Domain.Entities.OutfitClothing", b =>
                {
                    b.Property<Guid>("OutfitId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClothingId")
                        .HasColumnType("TEXT");

                    b.HasKey("OutfitId", "ClothingId");

                    b.HasIndex("ClothingId");

                    b.ToTable("OutfitClothes");
                });

            modelBuilder.Entity("ClosetApp.Domain.Entities.OutfitWornRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OutfitId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("WornDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OutfitId");

                    b.ToTable("OutfitWornRecords");
                });

            modelBuilder.Entity("ClosetApp.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Category = 0,
                            Color = "#D8B7A3",
                            CreatedAt = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "韩系",
                            UpdatedAt = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Category = 0,
                            Color = "#C8C2B8",
                            CreatedAt = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "极简",
                            UpdatedAt = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Category = 0,
                            Color = "#B7C4B2",
                            CreatedAt = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "通勤",
                            UpdatedAt = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            Category = 0,
                            Color = "#E7C7C0",
                            CreatedAt = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "甜妹",
                            UpdatedAt = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            Category = 0,
                            Color = "#C89B7B",
                            CreatedAt = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "美式",
                            UpdatedAt = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            Category = 0,
                            Color = "#C4A98F",
                            CreatedAt = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "复古",
                            UpdatedAt = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            Category = 0,
                            Color = "#A8B5A0",
                            CreatedAt = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Clean Fit",
                            UpdatedAt = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            Category = 0,
                            Color = "#D4A5C9",
                            CreatedAt = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Y2K",
                            UpdatedAt = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            Category = 1,
                            Color = "#E88D8D",
                            CreatedAt = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "约会",
                            UpdatedAt = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            Category = 1,
                            Color = "#8BA8D9",
                            CreatedAt = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "上班",
                            UpdatedAt = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            Category = 1,
                            Color = "#A8D4A8",
                            CreatedAt = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "出游",
                            UpdatedAt = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            Category = 1,
                            Color = "#D4A5E8",
                            CreatedAt = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "派对",
                            UpdatedAt = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("ClosetApp.Domain.Entities.ClothingTag", b =>
                {
                    b.HasOne("ClosetApp.Domain.Entities.Clothing", "Clothing")
                        .WithMany("ClothingTags")
                        .HasForeignKey("ClothingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClosetApp.Domain.Entities.Tag", "Tag")
                        .WithMany("ClothingTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clothing");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("ClosetApp.Domain.Entities.Favorite", b =>
                {
                    b.HasOne("ClosetApp.Domain.Entities.Outfit", "Outfit")
                        .WithMany("Favorites")
                        .HasForeignKey("OutfitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Outfit");
                });

            modelBuilder.Entity("ClosetApp.Domain.Entities.OutfitClothing", b =>
                {
                    b.HasOne("ClosetApp.Domain.Entities.Clothing", "Clothing")
                        .WithMany("OutfitClothes")
                        .HasForeignKey("ClothingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClosetApp.Domain.Entities.Outfit", "Outfit")
                        .WithMany("OutfitClothes")
                        .HasForeignKey("OutfitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clothing");

                    b.Navigation("Outfit");
                });

            modelBuilder.Entity("ClosetApp.Domain.Entities.OutfitWornRecord", b =>
                {
                    b.HasOne("ClosetApp.Domain.Entities.Outfit", "Outfit")
                        .WithMany("WornRecords")
                        .HasForeignKey("OutfitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Outfit");
                });

            modelBuilder.Entity("ClosetApp.Domain.Entities.Clothing", b =>
                {
                    b.Navigation("ClothingTags");

                    b.Navigation("OutfitClothes");
                });

            modelBuilder.Entity("ClosetApp.Domain.Entities.Outfit", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("OutfitClothes");

                    b.Navigation("WornRecords");
                });

            modelBuilder.Entity("ClosetApp.Domain.Entities.Tag", b =>
                {
                    b.Navigation("ClothingTags");
                });
#pragma warning restore 612, 618
        }
    }
}
